title: [30 天精通 Git 版本控管]
description: [由於 Git 版本控管無論在版控觀念與工具使用上，都與傳統集中式版控工具差異甚大，因此造成了不小的學習門檻，在未來的３０天內，希望能讓大家完整了解 Git 版本控管的精髓之處，並整理我的學習心得與我們公司從 Subversion 轉至 Git 的過程中所遭遇的問題與解決方法。]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme